import type { Metadata } from "next";
import { Aref_Ruqaa, Inter } from "next/font/google";
import "./globals.css";
import Layout from "./components/nav/Layout";
import Menu from "./components/menu/menu";
import AuthProvider from "@/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
      <html lang="en">
        <body className={inter.className}>
          <Layout />
          {/* <Menu /> */}
          <main className="mx-auto flex max-w-7xl items-center justify-between p-6 lg:px-8">
            {children}
          </main>
        </body>
      </html>
    </AuthProvider>
  );
}
